// SKILL-01/02/03 and D-105/D-110/D-111/D-129: what `renderSkill` and `skillTargets` produce, asserted over
// the whole render output rather than over a named role, so every definition a later plan adds inherits
// these gates the moment it lands.
import { readdirSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import type { Tags } from 'yaml';
import { allSkillDirs, contentHash, markerHash, renderSkill, skillDirs, skills, skillTargets, withoutMarker } from '../src/index.js';
import type { SkillKey } from '../src/index.js';
import type { AccordConfig } from '../src/index.js';
import { DONE_RULES, READY_RULES } from '../src/gate/rules.js';
import { RULES } from '../src/lint/rules.js';
import { deniedNames } from '../../../test/helpers/denied.js';

const skillsDir = fileURLToPath(new URL('../skills/', import.meta.url));
const BOM = String.fromCharCode(0xfeff);
const FRONTMATTER = /^---\n([\s\S]*?)\n---(?:\n|$)/;

// STACK.md Decision 2: core schema, numerics stay strings.
const stringNumerics = (tags: Tags) =>
  tags.filter((t) => !/int|float/.test(typeof t === 'string' ? t : t.tag));

const normalise = (text: string) =>
  (text.startsWith(BOM) ? text.slice(1) : text).replace(/\r\n/g, '\n');

/** The rendered frontmatter block parsed with yaml, or null when there is none. A `[a-z-]+:` scan would also
 *  match prose in a body — the block is machine-written and small, so parsing it is both safer and shorter. */
function frontmatter(md: string): Record<string, unknown> | null {
  const m = FRONTMATTER.exec(md);
  return m ? (parse(m[1], { schema: 'core', customTags: stringNumerics }) as Record<string, unknown>) : null;
}

const names = Object.keys(skills) as SkillKey[];

const config = (over: Partial<AccordConfig> = {}): AccordConfig => ({
  accord: '0.1.0',
  profile: 'build',
  tracker: { adapter: 'none' },
  design: { tokens: 'src/styles/tokens.css' },
  roles: ['ba', 'dev', 'designer'],
  runtimes: ['claude', 'codex'],
  ...over,
});

describe('rendered skills', () => {
  it('a role renders spec frontmatter, then the marker, then the body', () => {
    const text = renderSkill('designer/SKILL.md');
    const lines = text.split('\n');
    expect(lines[0]).toBe('---');
    const close = lines.indexOf('---', 1);
    expect(close).toBeGreaterThan(0);
    expect(lines[close + 1]).toMatch(/^<!-- generated by accord skills sync /);
  });

  it('rendered frontmatter is inside the six spec fields and drops the authoring keys (D-106)', () => {
    const fm = frontmatter(renderSkill('designer/SKILL.md'));
    expect(fm).not.toBeNull();
    expect(fm?.name).toBe('accord-designer');
    const six = ['name', 'description', 'license', 'compatibility', 'metadata', 'allowed-tools'];
    expect(Object.keys(fm ?? {}).filter((k) => !six.includes(k))).toEqual([]);
    expect(Object.keys(fm ?? {})).toContain('description');
  });

  it('skillTargets writes one role into both target directories (D-108)', () => {
    const paths = skillTargets(config()).map((f) => f.path);
    expect(paths).toContain('.claude/skills/accord-designer/SKILL.md');
    expect(paths).toContain('.agents/skills/accord-designer/SKILL.md');
    expect(paths).toContain('.claude/skills/accord-dev/SKILL.md');
    expect(paths).toContain('.claude/skills/accord-ba/SKILL.md');
    // All three roles in the `roles` enum are now authored, so the skip branch in `skillTargets` has no
    // valid roster left that exercises it. The cast is what keeps that branch covered: a roster naming a
    // role with no definition renders nothing rather than throwing, which is what lets a future role be
    // added to the enum before its workflow is written.
    const unauthored = skillTargets(config({ roles: ['qa'] as unknown as AccordConfig['roles'] }));
    expect(unauthored).toEqual([]);
  });

  it('allSkillDirs is the whole table and a superset of every roster (D-113)', () => {
    // The orphan scan opens this set, not `skillDirs(config)`: a directory abandoned by dropping a runtime
    // is by definition no longer declared, so the declared subset can never reach it. The literal is pinned
    // because `allSkillDirs` reads only the table — a config value arriving here would move it (T-06-01).
    expect(allSkillDirs()).toEqual(['.agents/skills', '.claude/skills']);
    const runtimes: AccordConfig['runtimes'] = ['claude', 'codex', 'cursor', 'copilot'];
    for (const runtime of runtimes) {
      for (const dir of skillDirs(config({ runtimes: [runtime] }))) {
        expect(allSkillDirs(), runtime).toContain(dir);
      }
    }
  });
});

describe('bundled references', () => {
  it('a reference renders with no frontmatter block, marker first (D-108)', () => {
    const text = renderSkill('shared/prototype.md');
    expect(text.startsWith('---')).toBe(false);
    expect(text.split('\n')[0]).toMatch(/^<!-- generated by accord skills sync /);
    expect(frontmatter(text)).toBeNull();
  });

  it('a loaded reference lands beside its role under both directories, keyed by basename', () => {
    const files = skillTargets(config());
    const designer = files.filter((f) => f.path.includes('/accord-designer/'));
    expect(designer.map((f) => f.path)).toEqual([
      '.agents/skills/accord-designer/SKILL.md',
      '.agents/skills/accord-designer/prototype.md',
      '.claude/skills/accord-designer/SKILL.md',
      '.claude/skills/accord-designer/prototype.md',
    ]);
    // D-119: duplication is in the output, never in the source — and the assertion cannot pass on two
    // empty strings, which is the failure mode templates.test.ts:86 guards against.
    const copies = designer.filter((f) => f.path.endsWith('/prototype.md')).map((f) => f.text);
    expect(copies[0].length).toBeGreaterThan(0);
    expect(copies[0]).toBe(copies[1]);
    // D-108: the relative reference is what makes one text correct in both directories.
    expect(files.find((f) => f.path === '.claude/skills/accord-designer/SKILL.md')?.text).toContain(
      './prototype.md',
    );
  });

  it('only a role definition is named SKILL.md, and no directory holds two (Cursor walks recursively)', () => {
    for (const name of names) {
      if (name.endsWith('/SKILL.md')) expect(name.split('/').length, name).toBe(2);
      else expect(name.split('/').at(-1), name).not.toBe('SKILL.md');
    }
    const perDir = new Map<string, number>();
    for (const { path } of skillTargets(config())) {
      if (!path.endsWith('/SKILL.md')) continue;
      const dir = path.slice(0, -'/SKILL.md'.length);
      perDir.set(dir, (perDir.get(dir) ?? 0) + 1);
    }
    expect(perDir.size).toBeGreaterThan(0);
    expect([...perDir].filter(([, n]) => n !== 1)).toEqual([]);
  });
});

describe('generated module', () => {
  it('generated module matches skills/ (drift)', () => {
    const onDisk = readdirSync(skillsDir, { recursive: true, withFileTypes: true })
      .filter((d) => d.isFile() && /\.md$/.test(d.name))
      .map((d) => relative(skillsDir, join(d.parentPath, d.name)).split(sep).join('/'))
      .sort();
    expect(Object.keys(skills), 'skill file set drifted: run npm run gen').toEqual(onDisk);
    for (const name of onDisk) {
      const text = normalise(readFileSync(join(skillsDir, name), 'utf8'));
      expect(skills[name as SkillKey], `${name} drifted: run npm run gen`).toBe(text);
    }
  });

  it('keys are posix and LF and no BOM on disk', () => {
    expect(names.length).toBeGreaterThan(0);
    for (const name of names) {
      expect(name, `${name} has a backslash`).not.toContain('\\');
      const raw = readFileSync(join(skillsDir, name), 'utf8');
      expect(raw, `${name} has CR`).not.toContain('\r');
      expect(raw.startsWith(BOM), `${name} has BOM`).toBe(false);
    }
  });
});

// Everything below iterates the whole render output rather than a named role, so a definition added by a
// later plan inherits these gates the moment it lands — no plan has to restate a criterion to be covered.
const SPEC_FIELDS = ['name', 'description', 'license', 'compatibility', 'metadata', 'allowed-tools'];

// D-129. The Agent Skills spec's own hard ceiling is 500 lines; this is the editorial one behind D-114's
// "one page", and it exists because prose without a number behind it drifts.
const MAX_SKILL_LINES = 120;

/** The commands the CLI actually registers, longest path first so `gate ready` wins over a bare `gate`. */
const COMMAND = /\baccord (gate ready|gate done|new ticket|skills sync|lint|status)\b/g;

/** The rendered text with its frontmatter block and its marker line removed — the prose a reader receives. */
const bodyOf = (text: string) => withoutMarker(text).replace(FRONTMATTER, '');

const dirOf = (path: string) => path.slice(0, path.lastIndexOf('/'));
const baseOf = (path: string) => path.slice(path.lastIndexOf('/') + 1);

const output = skillTargets(config());
const skillFiles = output.filter((f) => f.path.endsWith('/SKILL.md'));

describe('render output invariants', () => {
  it('has files to check', () => {
    // A silently empty render would make every assertion below vacuous.
    expect(output.length).toBeGreaterThan(0);
    expect(skillFiles.length).toBeGreaterThan(0);
  });

  it('every file carries exactly one marker whose hash recomputes (D-110, D-111)', () => {
    for (const { path, text } of output) {
      const stored = markerHash(text);
      expect(stored, `${path} has no marker`).toBeDefined();
      const bare = withoutMarker(text);
      // Removing once leaves none: that is what makes "exactly one" true without a second regex here.
      expect(markerHash(bare), `${path} carries more than one marker`).toBeUndefined();
      expect(contentHash(bare), `${path} marker hash does not recompute`).toBe(stored);
    }
  });

  it('every SKILL.md name equals its parent directory (spec; RESEARCH.md Pitfall 3)', () => {
    for (const { path, text } of skillFiles) {
      expect(frontmatter(text)?.name, path).toBe(baseOf(dirOf(path)));
    }
  });

  it('every SKILL.md frontmatter is inside the six spec fields and carries the two required ones', () => {
    for (const { path, text } of skillFiles) {
      const fm = frontmatter(text);
      expect(fm, path).not.toBeNull();
      const keys = Object.keys(fm ?? {});
      expect(keys.filter((k) => !SPEC_FIELDS.includes(k)), path).toEqual([]);
      expect(keys, path).toContain('name');
      expect(keys, path).toContain('description');
    }
  });

  it('every SKILL.md opens on the gate (SKILL-04, D-128)', () => {
    for (const { path, text } of skillFiles) {
      const found = [...bodyOf(text).matchAll(COMMAND)];
      // Guard the guard: a body naming no command is a failure, not a free pass.
      expect(found.length, `${path} names no accord command`).toBeGreaterThan(0);
      // Per file, never a uniqueness check across files: all three roles opening on the same call is the
      // intent of D-128, not a collision.
      expect(found[0][1], path).toBe('gate ready');
    }
  });

  it('every SKILL.md is at most MAX_SKILL_LINES lines (D-129)', () => {
    for (const { path, text } of skillFiles) {
      expect(text.split('\n').length, path).toBeLessThanOrEqual(MAX_SKILL_LINES);
    }
  });

  it('every relative reference resolves inside the same render, for more than one roster (D-110)', () => {
    // RESEARCH.md Pitfall 4: running this for the full roster only is the shape that misses the bug — a
    // filtering change can drop a file a SKILL.md still names.
    let seen = 0;
    for (const files of [output, skillTargets(config({ roles: ['ba', 'dev'] }))]) {
      const present = new Set(files.map((f) => f.path));
      const dead: string[] = [];
      for (const { path, text } of files) {
        for (const ref of text.matchAll(/\.\/([A-Za-z0-9._-]+)/g)) {
          seen++;
          const resolved = dirOf(path) + '/' + ref[1];
          if (!present.has(resolved)) dead.push(`${path}: ${ref[0]}`);
        }
      }
      expect(dead).toEqual([]);
    }
    expect(seen, 'no relative reference was found at all').toBeGreaterThan(0);
  });

  it('no backslash in any emitted path or any rendered text (D-51)', () => {
    for (const { path, text } of output) {
      expect(path, path).not.toContain('\\');
      const offender = text.split('\n').find((line) => line.includes('\\'));
      expect(offender, `${path}: ${String(offender)}`).toBeUndefined();
    }
  });

  it('no rendered text sends its reader to a file that exists only in this repository', () => {
    // Two forms of one defect. `packages/` is accord's own monorepo layout, which an npx user does not
    // have; `prototype-header.html` is a template that ships but that no shipped command writes into a
    // user's repository. Either way the reader is told to open something they cannot reach.
    // If a later phase's `accord init` scaffolds the header template into a user repository, the second
    // literal comes off this list in the same change that makes the reference true — never before.
    // Guarded against a vacuous pass by the `has files to check` case at the top of this describe.
    const REPO_ONLY = ['packages/', 'prototype-header.html'];
    const offenders: string[] = [];
    for (const { path, text } of output) {
      text.split('\n').forEach((line, i) => {
        if (REPO_ONLY.some((name) => line.includes(name))) offenders.push(`${path}:${i + 1}: ${line}`);
      });
    }
    expect(offenders).toEqual([]);
  });

  it('the marker claims generation and nothing more (RESEARCH.md Security Domain V6)', () => {
    // FNV-1a is a drift detector. Wording the marker as tamper evidence would be a false claim, so the two
    // words that would make it one are forbidden. Split literals, as templates.test.ts:102 does, so this
    // file does not contain them verbatim and trip the scan it is running.
    const forbidden = [new RegExp('verif' + 'ied', 'i'), new RegExp('sign' + 'ed', 'i')];
    for (const { path, text } of output) {
      const marker = text.split('\n').find((line) => markerHash(line) !== undefined) as string;
      for (const word of forbidden) expect(marker, `${path}: ${marker}`).not.toMatch(word);
    }
  });

  it('no rendered text names another tool, plugin, harness, or planning system (CLAUDE.md)', () => {
    // One assertion over the whole render output, so the prose plans 06-02 and 06-04 add is covered without
    // either plan restating the criterion. The list and the scan moved out of this file to `helpers/denied.ts`
    // in 07-04, when Phase 7 gave the same constraint three more shipped surfaces to cover, and on again to
    // `test/helpers/denied.ts` at the repository root in 07-14, when the published CLI bundle became a surface
    // the other package's tests had to scan too; the outcome here is unchanged.
    // Guarded against a vacuous pass by the `has files to check` case at the top of this describe.
    expect(deniedNames(output)).toEqual([]);
  });

  it('no rendered line carries the `Result:` or `Evidence:` label behind a list marker', () => {
    // `packages/core/src/load/verification.ts` anchors both labels at column 0 — `/^Result:/` and
    // `/^Evidence:/`, with no list-marker or leading-whitespace stripping. A brief that shows either
    // label behind a bullet therefore teaches a shape whose value the parser drops. Every offender is
    // collected before the assertion, so a RED names all of them at once rather than aborting on the
    // first. Guarded against a vacuous pass by the `has files to check` case at the top of this describe.
    const BULLETED_LABEL = /^\s*[-*+]\s+.*\b(?:Result|Evidence):/;
    const offenders: string[] = [];
    for (const { path, text } of output) {
      text.split('\n').forEach((line, i) => {
        if (BULLETED_LABEL.test(line)) offenders.push(`${path}:${i + 1}: ${line}`);
      });
    }
    expect(offenders).toEqual([]);
  });

  it('the review brief shows both verification labels at the start of a line', () => {
    // The case above only proves no brief BULLETS the labels; deleting step 2 outright would pass it.
    // This one proves the brief still shows the shape a reviewer is meant to copy.
    const review = output.find((f) => f.path === '.claude/skills/accord-dev/review.md')?.text ?? '';
    expect(review.length, 'accord-dev/review.md is missing from the render output').toBeGreaterThan(0);
    const lines = review.split('\n');
    expect(lines.some((l) => l.startsWith('Result:')), 'no line begins with the Result label').toBe(true);
    expect(lines.some((l) => l.startsWith('Evidence:')), 'no line begins with the Evidence label').toBe(true);
  });

  it('the prototype brief names no accord command before its step 4 heading', () => {
    // What this protects: the brief describes the work and then names the command; it does not preview
    // what the command will say. The case pins POSITION, not content — it would not have caught the
    // scope claim deleted from step 4's first paragraph, which sat after the heading. The content half
    // ("the prose states nothing about what a command covers") stays a recorded manual read, because a
    // pattern cannot tell a legitimate D-128 naming from a restatement without the semantics of which
    // noun a quantifier modifies.
    const body = bodyOf(output.find((f) => f.path === '.claude/skills/accord-dev/prototype.md')?.text ?? '');
    expect(body.length, 'accord-dev/prototype.md is missing from the render output').toBeGreaterThan(0);
    const lines = body.split('\n');
    const step4 = lines.findIndex((l) => /^## 4\. /.test(l));
    // Guard the guard: no step 4 heading, or no command named at or after it, is a failure not a pass.
    expect(step4, 'no step 4 heading was found').toBeGreaterThan(-1);
    const named = (text: string) => [...text.matchAll(COMMAND)].map((m) => m[0]);
    expect(
      named(lines.slice(step4).join('\n')).length,
      'no accord command is named at or after step 4',
    ).toBeGreaterThan(0);
    expect(named(lines.slice(0, step4).join('\n'))).toEqual([]);
  });

  it('no rendered text restates a rule the CLI enforces (SKILL-04, D-148)', () => {
    // A skill names the command; what the command checks is the command's own output to state. A
    // paraphrase in a skill body is a second, unversioned copy of the engine that nothing keeps in step.
    // The rule ids are computed from the live tables rather than listed, so a rule a later phase adds is
    // covered here with no edit. Line numbers are relative to the body, which is what the scan reads.
    const ruleIds = [...new Set([...RULES, ...READY_RULES, ...DONE_RULES].map((r) => r.id))];
    // `warning` is a finding level, and reporting a level is the CLI's job. `error` is deliberately not
    // here (A-16): every occurrence in the definitions is about the reader's own software — an EARS
    // example, a review dimension, a stack trace — never about a finding level.
    const LEVEL = /\bwarnings?\b/i;
    // A skill names `accord gate ready <id>` or `accord gate done <id>`, never the state the command
    // reports. Frontmatter is out of scope because the scan runs on the body: `description:` is how a
    // runtime decides whether to load the skill at all, and a code span there would not read as prose.
    const VERDICT = /\b(?:Ready|Done)\b/;
    // The subjects the READY_PROMOTE rules read. Each is legitimate on its own — the offence is naming
    // one in the same paragraph as the command that checks it.
    const PROMOTED = ['## Open questions', 'assumptions:', 'status: draft', 'TODO'];

    const offenders: { path: string; line: number; text: string }[] = [];
    let commands = 0;
    for (const { path, text } of output) {
      const body = bodyOf(text);
      body.split('\n').forEach((line, i) => {
        const hit = (ban: string) => offenders.push({ path, line: i + 1, text: `${ban}: ${line.trim()}` });
        for (const id of ruleIds) if (line.includes(id)) hit('rule id');
        if (LEVEL.test(line)) hit('finding level');
        if (VERDICT.test(line)) hit('gate verdict');
      });
      // Paragraph scope, not line and not section: every finding of this shape wraps across two or three
      // lines, while a section may legitimately run a gate and, separately, teach what belongs under a
      // heading. `matchAll` rather than `.test()` because COMMAND carries the `g` flag and is shared.
      let line = 1;
      for (const para of body.split('\n\n')) {
        const named = [...para.matchAll(COMMAND)].length;
        commands += named;
        if (named > 0) {
          const first = para.split('\n')[0].trim();
          for (const promoted of PROMOTED) {
            if (para.includes(promoted)) {
              offenders.push({ path, line, text: `command beside ${promoted}: ${first}` });
            }
          }
        }
        line += para.split('\n').length + 1;
      }
    }
    // Guard the guard: a render that stopped producing text, or one that named no command at all, fails
    // here rather than passing the assertion below on an empty scan.
    expect(output.length, 'the render is empty').toBeGreaterThan(0);
    expect(commands, 'no accord command was named anywhere in the render').toBeGreaterThan(0);
    // Code-point order, never localeCompare, so the failure output is byte-identical on every host.
    const cmp = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
    offenders.sort((a, b) => cmp(a.path, b.path) || a.line - b.line || cmp(a.text, b.text));
    expect(offenders.map((o) => `${o.path}:${o.line}: ${o.text}`)).toEqual([]);
  });
});

// SKILL-06/07/12, D-115 part 1, D-119: what a user actually receives from the `dev` definition. Asserted over
// the RENDERED text rather than the source, because the rendered text is the thing a runtime loads. The
// manual half of ROADMAP criterion 7 — running the wrong-plan fixture through the plan-review step and
// recording the `## Plan` before and after — is deliberately not here: the subject is model behaviour and
// the "No API keys" constraint rules out running a model in the suite (D-115).
const devSkill = output.find((f) => f.path === '.claude/skills/accord-dev/SKILL.md')?.text ?? '';
const devBody = bodyOf(devSkill);

/** The first line of every top-level numbered step, in body order. */
const stepLines = devBody.split('\n').filter((line) => /^\d+\. /.test(line));

/** One step and everything indented under it, up to the next top-level step. */
function stepBlock(body: string, match: RegExp): string {
  const lines = body.split('\n');
  const start = lines.findIndex((line) => /^\d+\. /.test(line) && match.test(line));
  if (start === -1) return '';
  const after = lines.findIndex((line, i) => i > start && /^\d+\. /.test(line));
  return lines.slice(start, after === -1 ? undefined : after).join('\n');
}

const PLAN_REVIEW = /\bplan\b[^\n]*\breview/i;
const IMPLEMENT = /^\d+\. Implement\b/;

describe('dev workflow structure', () => {
  it('renders as a role with its four bundled files reachable by relative path (SKILL-09, D-108)', () => {
    expect(devSkill.length, 'accord-dev/SKILL.md is missing from the render output').toBeGreaterThan(0);
    for (const ref of ['./debug.md', './review.md', './prototype.md']) expect(devBody, ref).toContain(ref);
    const present = new Set(output.map((f) => f.path));
    for (const name of ['SKILL.md', 'debug.md', 'review.md', 'code-review.md', 'prototype.md']) {
      expect(present.has('.claude/skills/accord-dev/' + name), name).toBe(true);
    }
  });

  it('reviews the plan before the code is written (SKILL-12, D-115 part 1)', () => {
    // The ordered array rather than two indexes, so a failure prints the actual order (templates.test.ts:70).
    const order = stepLines
      .filter((line) => PLAN_REVIEW.test(line) || IMPLEMENT.test(line))
      .map((line) => (PLAN_REVIEW.test(line) ? 'plan-review' : 'implement'));
    expect(order).toEqual(['plan-review', 'implement']);
  });

  it('the plan review reads no code and edits only the plan (SKILL-12)', () => {
    const block = stepBlock(devBody, PLAN_REVIEW);
    expect(block.length, 'no plan-review step was found').toBeGreaterThan(0);
    // Two independent phrases, never one copied sentence: the substance is the boundary, not the wording.
    expect(block, 'the plan review does not say it reads no code').toMatch(/\bread(s)? no code\b/i);
    expect(block, 'the plan review does not say it edits only the plan').toMatch(/\bedits? only\b[^\n]*## Plan/i);
  });

  it('the code review opens a fresh context, gets review.md, and names no runtime product (SKILL-06, D-109)', () => {
    const block = stepBlock(devBody, /\bcode\b[^\n]*\breview/i);
    expect(block.length, 'no code-review step was found').toBeGreaterThan(0);
    expect(block).toMatch(/\bfresh context\b/i);
    expect(block).toContain('./review.md');
    // D-109: one text, identical in every runtime. Split literals so this file does not trip its own scan.
    const PRODUCTS = ['Cur' + 'sor', 'Cop' + 'ilot', 'Cod' + 'ex', 'Claude ' + 'Code'];
    const named = PRODUCTS.filter((p) => new RegExp('\\b' + p + '\\b', 'i').test(block));
    expect(named).toEqual([]);
  });

  it('exactly one rendered file tells its reader to write `verified` (SKILL-07)', () => {
    // An imperative write verb immediately before the key, which is what distinguishes an instruction to this
    // file's reader from code-review.md's third-person mention of the developer ticking it later.
    const WRITES = /\b(ticks?|writes?|records?)\s+`?verified/i;
    const authors = output.filter((f) => WRITES.test(f.text)).map((f) => f.path);
    expect([...new Set(authors.map(baseOf))]).toEqual(['SKILL.md']);
    expect(authors).toContain('.claude/skills/accord-dev/SKILL.md');
  });
});

describe('the review context write boundary (ROADMAP criterion 4)', () => {
  // The two files, and the only two files, the fresh review context receives.
  const briefs = output.filter((f) =>
    ['.claude/skills/accord-dev/review.md', '.claude/skills/accord-dev/code-review.md'].includes(f.path),
  );
  const VERIFICATION = 'accord/tickets/<id>/verification.md';

  it('has both briefs to check', () => {
    expect(briefs.map((f) => f.path)).toEqual([
      '.claude/skills/accord-dev/code-review.md',
      '.claude/skills/accord-dev/review.md',
    ]);
  });

  it('the brief names verification.md and says it reports rather than changes what it judges', () => {
    const review = briefs.find((f) => f.path.endsWith('/review.md'))?.text ?? '';
    expect(review).toContain(VERIFICATION);
    // Two independent phrases again: the boundary, not a sentence.
    expect(review, 'the brief does not say it reports on the change').toMatch(/\breport on the change\b/i);
    expect(review, 'the brief does not say it changes nothing').toMatch(/\bdo not change it\b/i);
  });

  it('names exactly one accord/-rooted path across both briefs, and it is verification.md', () => {
    // Named at all, with no write-verb heuristic. Every other path these two texts mention is a relative
    // ./ reference, which is not accord/-rooted, while any second artifact a reviewer could be told to
    // write is. A second write target makes this go red.
    const named = new Set<string>();
    for (const { text } of briefs) for (const m of text.matchAll(/accord\/[A-Za-z0-9_<>./-]+/g)) named.add(m[0]);
    // Guard the guard: a brief naming no write target at all is not a pass.
    expect(named.size, 'neither brief names an accord/ path').toBeGreaterThan(0);
    expect([...named].sort()).toEqual([VERIFICATION]);
  });
});

describe('a shared reference renders once per role that loads it (D-119)', () => {
  it('the two prototype.md copies are byte-identical, non-empty, and at two different paths', () => {
    const copies = output.filter(
      (f) => f.path.endsWith('/prototype.md') && f.path.startsWith('.claude/skills/'),
    );
    expect(copies.map((f) => f.path)).toEqual([
      '.claude/skills/accord-designer/prototype.md',
      '.claude/skills/accord-dev/prototype.md',
    ]);
    expect(copies[0].path).not.toBe(copies[1].path);
    expect(copies[0].text.length).toBeGreaterThan(0);
    expect(copies[0].text).toBe(copies[1].text);
  });
});

// SKILL-05, D-118, D-125: what a user receives from the `ba` definition, asserted over the RENDERED texts.
const baSkill = output.find((f) => f.path === '.claude/skills/accord-ba/SKILL.md')?.text ?? '';
const baBody = bodyOf(baSkill);
const baFile = (name: string) =>
  output.find((f) => f.path === '.claude/skills/accord-ba/' + name)?.text ?? '';

describe('ba workflow structure', () => {
  it('renders as a role with its three bundled files reachable by relative path (SKILL-01, D-108)', () => {
    expect(baSkill.length, 'accord-ba/SKILL.md is missing from the render output').toBeGreaterThan(0);
    const present = new Set(output.map((f) => f.path));
    for (const name of ['SKILL.md', 'setup.md', 'story.md', 'ready.md']) {
      expect(present.has('.claude/skills/accord-ba/' + name), name).toBe(true);
    }
    // `ready.md` is referenced from story.md, not from SKILL.md; without its `loads:` entry it would never
    // render and story.md's `./ready.md` would be a dead reference.
    expect(baFile('story.md')).toContain('./ready.md');
  });

  it('branches on config.profile at its first step after the gate (D-118)', () => {
    const block = stepBlock(baBody, /\bprofile\b/i);
    expect(block.length, 'no step reads the profile').toBeGreaterThan(0);
    expect(block, 'the branch step does not name config.profile').toContain('config.profile');
    // Both branch targets in the one step, and `./setup.md` beside the `build` profile it belongs to.
    expect(block, 'the build branch does not point at setup.md').toMatch(/`build`[\s\S]*\.\/setup\.md/);
    expect(block, 'the other branch does not point at story.md').toContain('./story.md');
  });

  it('keeps the ticket draft and teaches where an undecided thing is recorded (SKILL-05)', () => {
    // Narrowed under SKILL-04/D-148 (owner decision 2026-09-17, option A'). This case used to require
    // `ba/SKILL.md` to enumerate the three subjects READY_PROMOTE reads, which is the restatement D-148
    // ruled against. What survives is split by where each part is legitimate:
    //   - `draft` is the ticket status the BA sets, not a claim about what a gate checks, so it stays here.
    //   - the two recording places are asserted against `story.md`, which names them without a command
    //     beside them — the shape `no rendered text restates a rule the CLI enforces` permits.
    //   - a TODO marker is gone: it is nothing but `lint.sentinel`'s subject, and no wording of it in a
    //     skill body satisfies SKILL-04. The CLI reports it; the skill does not preview the report.
    // Asserted independently, not as one sentence, so one of them cannot be dropped silently.
    expect(baBody, 'the ticket status is never named').toContain('draft');
    const story = baFile('story.md');
    expect(story.length, 'accord-ba/story.md is missing from the render output').toBeGreaterThan(0);
    expect(story, 'open questions are not named as a place to record').toContain('## Open questions');
    expect(story, 'unconfirmed assumptions are not named as a place to record').toMatch(/`assumptions:`[\s\S]{0,60}`confirmed: false`/);
  });

  it('names accord status and the ticket as the way to pick work back up', () => {
    const block = stepBlock(baBody, /accord status/);
    expect(block.length, 'no step names `accord status`').toBeGreaterThan(0);
    expect(block, 'the resume step does not say what it is for').toMatch(/\bpick\b[^\n]*\bback up\b/i);
    expect(block, 'the resume step does not name the ticket').toMatch(/\bthe ticket\b/i);
  });

  it('the setup branch carries project and epic setup (ROADMAP criterion 6)', () => {
    const setup = baFile('setup.md');
    expect(setup.length, 'accord-ba/setup.md is missing from the render output').toBeGreaterThan(0);
    for (const literal of ['product/glossary.md', 'product/business-rules.md', 'accord new ticket', '--type epic']) {
      expect(setup, literal).toContain(literal);
    }
    // D-116: the convention has no schema behind it, so the workflow teaching it is half of its enforcement
    // and packages/core/templates/business-rules.md is the other half (templates.test.ts).
    expect(setup, 'the rejected-alternatives convention is not taught').toContain('Rejected:');
  });

  it('the readiness review is a fresh context with a narrow read and a narrower write (D-125)', () => {
    const ready = baFile('ready.md');
    expect(ready.length, 'accord-ba/ready.md is missing from the render output').toBeGreaterThan(0);
    // Two independent phrases per property, never one copied sentence.
    expect(ready, 'the brief does not say it is a fresh context').toMatch(/\bfresh context\b/i);
    expect(ready, 'the brief does not say it reads no code').toMatch(/\bread(s)? no code\b/i);
    expect(ready, 'the brief does not confine its writes').toMatch(/\bwrites? only\b[^\n]*## Open questions/i);
    // D-109 applies here too: one text, identical in every runtime.
    const PRODUCTS = ['Cur' + 'sor', 'Cop' + 'ilot', 'Cod' + 'ex', 'Claude ' + 'Code'];
    expect(PRODUCTS.filter((p) => new RegExp('\\b' + p + '\\b', 'i').test(ready))).toEqual([]);
  });

  it('exactly three roles render a SKILL.md (SKILL-01)', () => {
    // One runtime, so "exactly three" is a count over the whole render output rather than over a slice of
    // it: two runtimes turn the same three definitions into six files with three repeated directory names.
    const single = skillTargets(config({ runtimes: ['claude'] })).filter((f) => baseOf(f.path) === 'SKILL.md');
    expect(single.length).toBe(3);
    expect(single.map((f) => baseOf(dirOf(f.path))).sort()).toEqual([
      'accord-ba',
      'accord-designer',
      'accord-dev',
    ]);
  });
});

// ROADMAP criterion 6, final clause: "no session or handoff file exists anywhere". `anywhere` is the
// criterion's own word, so this runs over the whole render output — every rendered SKILL.md and every
// bundled reference — rather than over the role whose plan happened to add the assertion.
//
// It matches the ARTIFACT form and never the bare noun. The bare noun is how the render output legitimately
// says what a fresh context is ("otherwise a new session", the runtime-neutral phrasing D-109 requires once
// no runtime product may be named) and how `debug.md` says the ticket is the session. A matcher that flagged
// those would be answered by rewording true sentences, which is the one thing that would make a true
// criterion read as false. Split literals, as above, so this file does not trip the scan it runs.
const ARTIFACT = '(?:file|artifact|document|doc|note|log|state)s?';
const RESUME_ARTIFACT = new RegExp(
  '\\b' + 'hand' + 'off\\b|\\b' + 'sess' + 'ion[ -]?(?:' + ARTIFACT + '|\\.md)\\b',
  'i',
);

describe('no resume artifact anywhere in the render output (ROADMAP criterion 6)', () => {
  it('has files to scan, and a matcher that can still go red', () => {
    expect(output.length, 'nothing was scanned').toBeGreaterThan(0);
    // Guard the guard, one fixture per shape: a matcher narrowed until it cannot report an offender fails
    // here before it passes below.
    expect(RESUME_ARTIFACT.test('resume from the ' + 'hand' + 'off'), 'shape 1 matches nothing').toBe(true);
    expect(RESUME_ARTIFACT.test('write a ' + 'sess' + 'ion file first'), 'shape 2 matches nothing').toBe(true);
  });

  it('no rendered file names a resume artifact', () => {
    const offenders: string[] = [];
    for (const { path, text } of output) {
      text.split('\n').forEach((line, i) => {
        if (RESUME_ARTIFACT.test(line)) offenders.push(`${path}:${i + 1}: ${line.trim()}`);
      });
    }
    expect(offenders.sort()).toEqual([]);
  });
});
