// Emits src/generated/skills.ts from skills/**/*.md (D-105). Lives outside src/, so Node built-ins are allowed here.
// The raw source text ships, frontmatter and all: src/skills/render.ts calls the pure splitFrontmatter that
// already exists, and a second splitter written here would be a second thing to keep correct.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const dir = `${root}skills`;
// Keys are posix (`designer/SKILL.md`), never `designer\SKILL.md` — the same native-to-posix conversion
// packages/cli/src/load/fs.ts makes for a reported path (D-51).
const files = readdirSync(dir, { recursive: true, withFileTypes: true })
  .filter((d) => d.isFile() && /\.md$/.test(d.name))
  .map((d) => relative(dir, join(d.parentPath, d.name)).split(sep).join('/'))
  .sort();
const body = files
  .map((f) => {
    const text = readFileSync(join(dir, f), 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
    return `  ${JSON.stringify(f)}: ${JSON.stringify(text)},`;
  })
  .join('\n');
mkdirSync(`${root}src/generated`, { recursive: true });
writeFileSync(
  `${root}src/generated/skills.ts`,
  `// Generated by scripts/gen-skills.mjs from skills/**/*.md (D-105). Do not edit.\nexport const skills = {\n${body}\n} as const;\nexport type SkillKey = keyof typeof skills;\n`,
  'utf8',
);
console.log(`generated ${files.length} skills`);
