import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const generated = fileURLToPath(new URL('../README.md', import.meta.url));
const source = fileURLToPath(new URL('../../../README.md', import.meta.url));
const BOM = String.fromCharCode(0xfeff);
const BANNER =
  '<!-- Generated by packages/cli/scripts/gen-readme.mjs from the repository root README.md. Do not edit. -->';

const normalise = (text: string) => (text.startsWith(BOM) ? text.slice(1) : text).replace(/\r\n/g, '\n');

describe('generated README', () => {
  // normalise() the re-derived INPUT and read the generated file as-is. `.gitattributes` can hand a Windows
  // checkout a CRLF source; normalising both sides would hide exactly the drift the generator's own
  // normalisation exists to prevent, and normalising neither would go red on windows-latest only.
  it('matches the repository root README (drift)', () => {
    const expected = `${BANNER}\n\n${normalise(readFileSync(source, 'utf8'))}`;
    expect(readFileSync(generated, 'utf8'), 'packages/cli/README.md drifted: run npm run gen').toBe(expected);
  });

  it('LF and no BOM on disk', () => {
    const raw = readFileSync(generated, 'utf8');
    expect(raw, 'packages/cli/README.md has CR').not.toContain('\r');
    expect(raw.startsWith(BOM), 'packages/cli/README.md has BOM').toBe(false);
  });

  // A hand-edited file that silently loses its banner is a file the next reader will hand-edit again.
  it('names its generator on the first line', () => {
    const first = readFileSync(generated, 'utf8').split('\n')[0];
    expect(first, 'packages/cli/README.md lost its banner: run npm run gen').toContain('gen-readme.mjs');
  });
});
