// Emits packages/cli/README.md from the repository root README.md (D-156 defect 1). `files: ["dist",
// "README.md"]` publishes a file npm cannot reach outside the package folder, so the page was blank; a
// second hand-maintained README would drift instead. Lives outside src/, so Node built-ins are allowed here.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
// A Markdown comment, not a `//` line: npmjs.com renders anything else as body text.
const banner =
  '<!-- Generated by packages/cli/scripts/gen-readme.mjs from the repository root README.md. Do not edit. -->';
// Strip BOM, normalise to LF: the drift test compares byte-for-byte and CI runs on windows-latest.
const text = readFileSync(`${root}../../README.md`, 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
writeFileSync(`${root}README.md`, `${banner}\n\n${text}`, 'utf8');
console.log(`generated README.md from the root README (${text.length} chars)`);
