// Emits packages/cli/README.md from the repository root README.md (D-156 defect 1). `files: ["dist",
// "README.md"]` publishes a file npm cannot reach outside the package folder, so the page was blank; a
// second hand-maintained README would drift instead. Lives outside src/, so Node built-ins are allowed here.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
// A Markdown comment, not a `//` line: npmjs.com renders anything else as body text.
const banner =
  '<!-- Generated by packages/cli/scripts/gen-readme.mjs from the repository root README.md. Do not edit. -->';
// Strip BOM, normalise to LF: the drift test compares byte-for-byte and CI runs on windows-latest.
const source = readFileSync(`${root}../../README.md`, 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');

// The registry serves this page from its own origin, so a repository-relative link resolves to
// nothing there and the reader is sent to a 404 rather than to the document it names. Rewrite each
// one against the repository the manifest declares, which is also the repository provenance attests
// to at publish, so the two cannot disagree. Absolute links, protocol-relative links and anchors are
// left alone.
const repository = JSON.parse(readFileSync(`${root}package.json`, 'utf8')).repository.url;
const base = `${repository.replace(/^git\+/, '').replace(/\.git$/, '')}/blob/main/`;
const text = source.replace(/\]\((?!\w+:|\/\/|#)([^)]+)\)/g, (_, href) => `](${base}${href})`);

// An explicit destination lets the drift test run this generator rather than re-implement it; a test
// that re-derives the output is a test of its own copy of the rules.
const out = process.argv[2] ?? `${root}README.md`;
writeFileSync(out, `${banner}\n\n${text}`, 'utf8');
console.log(`generated README.md from the root README (${text.length} chars)`);
