// SKILL-02 rendering (D-106, D-111): one authored definition becomes the text that lands in a user's
// repository. The source frontmatter carries authoring keys (`kind`, `loads`) that must never ship, so the
// renderer keeps only the six Agent Skills spec fields and drops the rest; a bundled reference carries no
// spec frontmatter at all and renders with no `---` block, which is precisely why the marker cannot live
// inside frontmatter (D-111).
//
// The hash is FNV-1a 64-bit, hand-written on TextEncoder and BigInt for the same reason
// packages/core/src/gate/hash.ts is: core is isomorphic, so node:crypto is banned (CORE-01), and Web
// Crypto's subtle.digest would make rendering async for forty bytes. It is a drift detector and nothing
// more — it says whether a copy diverged, never that a copy is authentic.
import { Document, Scalar, isScalar, parse } from 'yaml';
import { splitFrontmatter, stringNumerics } from '../load/frontmatter.js';
import { skills } from '../generated/skills.js';
import type { SkillKey } from '../generated/skills.js';

const options = { schema: 'core', customTags: stringNumerics } as const;

// SKILL-02 is an allowlist, not a checklist: only `name` and `description` are required by the spec, so an
// absent optional field is simply not emitted. The order here is the order the rendered block carries, so
// the output is deterministic whatever order the source was authored in.
const SPEC_FIELDS = ['name', 'description', 'license', 'compatibility', 'metadata', 'allowed-tools'] as const;

// D-111: one HTML comment line, immediately after the closing `---` — frontmatter must start at line 1 or a
// runtime ignores it. It states generation, says do not edit, and carries the drift hash; it claims nothing
// about authenticity, because FNV-1a cannot support such a claim.
const MARKER_HEAD = '<!-- generated by accord skills sync - do not edit - ';
const MARKER_TAIL = ' -->';
// The trailing newline is part of the match, so removing the marker reproduces the text that was hashed.
const MARKER = /^<!-- generated by accord skills sync - do not edit - (fnv1a64:[0-9a-f]{16}) -->\n?/m;

const OFFSET = 0xcbf29ce484222325n;
const PRIME = 0x100000001b3n;
const MASK = 0xffffffffffffffffn;

/**
 * `fnv1a64:` plus 16 lowercase hex digits over the text as given. The caller owns normalisation (D-38) and
 * owns removing the marker line — a file read back from disk must be put through both before it can be
 * compared with a hash produced here (RESEARCH.md Pitfall 1).
 */
export function contentHash(text: string): string {
  let h = OFFSET;
  for (const byte of new TextEncoder().encode(text)) h = ((h ^ BigInt(byte)) * PRIME) & MASK;
  return 'fnv1a64:' + h.toString(16).padStart(16, '0');
}

/** The hash stored in a rendered file's marker, or undefined when the file carries no marker. */
export function markerHash(text: string): string | undefined {
  return MARKER.exec(text)?.[1];
}

/** The rendered text with its marker line removed — the exact input `contentHash` was given at render time. */
export function withoutMarker(text: string): string {
  return text.replace(MARKER, '');
}

/** The parsed source frontmatter of a definition; `{}` when it has none. */
function source(key: SkillKey): { yaml: Record<string, unknown>; body: string } {
  const text = skills[key];
  if (text === undefined) throw new Error('unknown skill definition: ' + key);
  const split = splitFrontmatter(text);
  const yaml = split.yaml === null ? {} : (parse(split.yaml, options) as Record<string, unknown>);
  return { yaml, body: split.body };
}

/**
 * D-106: which reference files a role definition pulls into its own directory, as source keys relative to
 * `packages/core/skills/`. Internal to `skills/` — `targets.ts` is the only caller, and the public API
 * exposes the rendered result rather than the authoring key that produced it.
 */
export function skillLoads(key: SkillKey): SkillKey[] {
  const loads = source(key).yaml.loads;
  return Array.isArray(loads) ? (loads as SkillKey[]) : [];
}

/**
 * The text that lands on disk. A `kind: role` definition renders its spec frontmatter, then the marker, then
 * the body; anything else renders the marker and the body alone (D-108: a bundled reference has no spec
 * frontmatter, which is what keeps it undiscoverable as a skill of its own).
 *
 * Pure: reads the generated module only, and returns the same text on every call.
 */
export function renderSkill(key: SkillKey): string {
  const { yaml, body } = source(key);
  let head = '';
  if (yaml.kind === 'role') {
    // D-45: strings core writes are double-quoted. Hand concatenation would break the moment a
    // `description` contained a colon, which is why the block goes through yaml's own serialiser.
    // A spec field that is not a plain string (`metadata` is a map) serialises with yaml's defaults.
    const doc = new Document({}, options);
    for (const field of SPEC_FIELDS) {
      if (!Object.hasOwn(yaml, field)) continue;
      const node = doc.createNode(yaml[field]);
      if (isScalar(node) && typeof yaml[field] === 'string') node.type = Scalar.QUOTE_DOUBLE;
      doc.set(field, node);
    }
    head = '---\n' + doc.toString({ lineWidth: 0 }).replace(/\n$/, '') + '\n---\n';
  }
  // D-111: the hash covers the rendered file with the marker line absent, so the same computation
  // reproduces it from a copy on disk — detecting both a changed definition and a hand-edited copy.
  return head + MARKER_HEAD + contentHash(head + body) + MARKER_TAIL + '\n' + body;
}
